import type { Post } from './types';

export const post: Post = {
  slug: 'trained-identity-vs-lora-vs-reference-image',
  title: 'Trained Identity vs LoRA vs Reference Image: Choosing a Consistency Method',
  metaTitle: 'Trained Identity vs LoRA vs Reference Image: Which to Use',
  metaDescription:
    'Three ways to keep a face consistent across generative output, compared on setup cost, drift rate, licensing exposure and what each one actually commits you to. With the threshold at which each becomes correct.',
  excerpt:
    'The right method depends almost entirely on how many assets the face has to survive. Below nine, one answer. Above nine, a different one.',
  published: '2026-07-02',
  author: 'Konstantinos Chatzimichail',
  section: 'Method',
  tags: ['Method', 'Consistency', 'Presenters'],
  keywords: [
    'trained identity AI video',
    'LoRA vs reference image',
    'AI character consistency methods',
    'consistent AI presenter',
    'AI avatar consistency',
    'character consistency AI video',
    'AI face consistency workflow',
  ],
  image: 'trained-identity',
  imageAlt:
    'Three columns of the same face, each generated by a different consistency method, with drift measured between them.',
  standfirst:
    'There are three practical ways to hold a face steady across generative output, and choosing wrongly costs you either a lot of setup you did not need or a lot of regeneration you could have avoided. The deciding variable is asset count, and the threshold is lower than most teams assume.',
  body: [
    {
      t: 'p',
      text: 'Character consistency is the problem that separates a nice clip from a campaign, and by 2026 there are three mature ways to attack it. They are not competing solutions to one problem. They solve the same symptom at three different levels of commitment.',
    },
    { t: 'h2', text: 'The three methods' },
    { t: 'h3', text: 'Reference image conditioning' },
    {
      t: 'p',
      text: 'Hand the model one or more images of the person and ask it to condition on them. Setup is minutes. Every modern video model supports it natively.',
    },
    {
      t: 'p',
      text: 'The weakness is that the reference is interpreted afresh each session, and interpretation drifts. Across two or three assets in one sitting it holds. Across nine assets made over three weeks, with a model version change in the middle, it does not.',
    },
    { t: 'h3', text: 'LoRA or equivalent lightweight fine-tune' },
    {
      t: 'p',
      text: 'Train a small adapter on a set of images so the identity is baked into the generation rather than supplied alongside it. Setup is hours plus a curated image set. Drift falls substantially.',
    },
    {
      t: 'p',
      text: 'The weaknesses are practical rather than technical. The adapter is tied to a base model, so a base model upgrade means retraining. And a badly curated training set bakes in whatever was over-represented in it, usually one lighting condition and one expression, which then appears in every output regardless of the prompt.',
    },
    { t: 'h3', text: 'Trained identity as a production artefact' },
    {
      t: 'p',
      text: 'What we mean by this is the adapter plus everything around it: a curated and documented image sheet, a written description of the identity in the terms the model responds to, a set of validated prompts, a record of which base model and version it was built against, the licence and consent file, and a per-shot check sheet.',
    },
    {
      t: 'p',
      text: 'Setup is a day or more. What you get is an artefact that survives a personnel change, a model upgrade and a legal review, which the other two do not.',
    },
    { t: 'h2', text: 'Compared on what matters' },
    {
      t: 'table',
      caption: 'Three consistency methods, compared operationally',
      head: ['', 'Reference image', 'LoRA', 'Trained identity'],
      rows: [
        ['Setup time', 'Minutes', 'Hours', 'A day or more'],
        ['Holds across', '2 to 3 assets, one session', '10 to 30 assets, one base model', 'A campaign, across upgrades'],
        ['Survives a model version change', 'No', 'Requires retraining', 'Yes, documented to rebuild'],
        ['Survives the operator leaving', 'No', 'Partly', 'Yes'],
        ['Consent file attached', 'Rarely', 'Sometimes', 'Always, by construction'],
        ['Cost to redo', 'Nothing', 'A few hours', 'A day'],
        ['Right when', 'One-off, one session', 'Volume, one campaign', 'A face you will use again'],
      ],
    },
    { t: 'h2', text: 'The threshold' },
    {
      t: 'p',
      text: 'The break-even is around nine assets. Below that, reference conditioning plus tight gating is cheaper overall even accounting for the regeneration. Above it, the regeneration cost from drift exceeds the setup cost of a trained identity, and it keeps exceeding it.',
    },
    {
      t: 'p',
      text: 'Nine is not a universal constant. It moves down when the face has to appear at close range, when the assets are produced across weeks rather than a day, or when several operators are involved. It moves up when the face is small in frame or the pieces are short.',
    },
    {
      t: 'note',
      title: 'The number to watch',
      text: 'Acceptance rate on presenter shots, logged per batch. Reference conditioning drifts across a multi-week campaign and a trained identity does not, so the gap widens the longer the campaign runs. Watch your own two numbers rather than anybody else’s: the point at which they diverge is the point the setup paid for itself.'
    },
    { t: 'h2', text: 'The licensing question, which is not optional' },
    {
      t: 'p',
      text: 'Every one of these methods is doing something to a person’s likeness, and the paperwork differs.',
    },
    {
      t: 'ul',
      items: [
        'A reference image of a real person needs a release for that use, and old photography releases almost never cover generative conditioning.',
        'A LoRA or trained identity built from a real person needs a release that explicitly permits derivative training, names the scope of output, states territory and duration, and says what happens to the trained artefact at the end of the term.',
        'A wholly synthetic identity needs no personal consent but does need a model licence cleared for commercial use, plus a reverse image search on the final face with the result recorded.',
      ],
    },
    {
      t: 'p',
      text: 'The consent file exists before the first render, not before the first delivery. This is the discipline that trained identity as a production artefact enforces by construction, and it is the main reason we treat it as a documented artefact rather than a file on somebody’s machine.',
    },
    { t: 'h2', text: 'What to do this week' },
    {
      t: 'ol',
      items: [
        'Count the assets the face has to appear in over the next quarter, not the next campaign. Most teams undercount by looking at one brief.',
        'If it is under nine and inside one session, use reference conditioning and spend the saved time on gating instead.',
        'If it is over nine, or spread across weeks, build the identity properly and document which base model it was built against.',
        'Either way, get the release signed before anything renders, covering derivative training explicitly.',
        'Log the presenter acceptance rate per batch. It is the number that tells you when you crossed the threshold, usually about a batch after you actually did.',
      ],
    },
    {
      t: 'cta',
      href: '/pipelines/identity-lock',
      label: 'Read the Identity Lock pipeline',
      text: 'The full pipeline, published with its gates, its consent requirements and the points at which a person decides.',
    },
  ],
  faqs: [
    {
      q: 'What is the difference between a reference image and a trained identity?',
      a: 'A reference image is supplied to the model at generation time and reinterpreted each session, so it drifts. A trained identity bakes the likeness into the generation and is documented as a production artefact with its base model version, prompt set, consent file and check sheet attached.',
    },
    {
      q: 'When is a LoRA worth training for character consistency?',
      a: 'Roughly above nine assets, or whenever the assets are produced across weeks rather than in one session. Below that threshold, reference conditioning plus tight per-shot gating is cheaper overall even accounting for regeneration.',
    },
    {
      q: 'Does a trained identity survive a model upgrade?',
      a: 'The adapter itself usually does not, because it is tied to a base model. What survives is the documentation: the curated image sheet, the identity description, the validated prompts and the recorded base version, which together make rebuilding a known job rather than a rediscovery.',
    },
    {
      q: 'What consent is needed to train a model on a real person?',
      a: 'A release that explicitly permits derivative training, names the scope of output, states territory and duration, and specifies what happens to the trained artefact at the end of the term. Photography releases drafted before generative production almost never cover this.',
    },
    {
      q: 'Is a trained identity worth the setup time?',
      a: 'Enough that it usually recovers a day of setup within about one batch, because the regeneration you stop paying for compounds across every asset. The size of the gain depends on your shot type and how long the campaign runs, so log presenter acceptance per batch and let your own numbers make the case.',
    },
  ],
  terms: ['character-consistency', 'master-plate', 'synthetic-ugc', 'cost-per-accepted-asset'],
  related: [
    'why-your-ai-video-looks-cheap-and-what-fixes-it',
    'synthetic-ugc-consent-likeness-and-disclosure-checklist',
    'how-we-keep-a-product-consistent-across-100-ai-generated-shots',
  ],
  resources: ['generative-film-shot-consistency-checklist', 'synthetic-ugc-consent-template'],
};
