import type { Post } from './types';

export const post: Post = {
  slug: 'who-owns-ai-generated-content',
  title: 'Who Owns AI-Generated Content? The Contract Questions That Actually Decide It',
  metaTitle: 'Who Owns AI-Generated Content? Rights, Contracts and Practice',
  metaDescription:
    'Copyright in purely machine-generated output is uncertain in most jurisdictions. What that means commercially, which contract terms decide ownership in practice, and the four clauses to check before signing anything.',
  excerpt:
    'The interesting question is not whether copyright subsists. It is what your contract says when it does not.',
  published: '2026-05-19',
  author: 'Konstantinos Chatzimichail',
  section: 'Compliance',
  tags: ['Compliance', 'Ethics', 'Buying'],
  keywords: [
    'who owns AI generated content',
    'AI copyright ownership',
    'AI generated image rights',
    'AI content licensing',
    'commercial use AI output',
    'AI output ownership contract',
  ],
  image: 'who-owns-ai-content',
  imageAlt: 'A contract page with four clauses highlighted.',
  standfirst:
    'In most jurisdictions, copyright requires human authorship, so purely machine-generated output may attract thin protection or none. That makes the contract the operative document: what the platform’s terms grant, what the studio assigns, what indemnity exists, and what happens if a model is withdrawn.',
  body: [
    {
      t: 'p',
      text: 'This is a working summary written by a production studio and not legal advice. It is also the conversation that stalls more generative projects than any technical problem, usually because the two sides are answering different questions.',
    },
    { t: 'h2', text: 'The copyright position, briefly' },
    {
      t: 'p',
      text: 'The dominant position across major jurisdictions is that copyright requires human authorship. Output generated by a model with minimal human contribution therefore sits somewhere between thin protection and none, with the line drawn differently in different places and still moving.',
    },
    {
      t: 'p',
      text: 'What tends to attract protection is the human contribution around the generation: the selection, the arrangement, the editing, the compositing, the sequencing, the written elements. A finished film assembled by people from generated components is a different object from a single unedited output, and it is treated as one.',
    },
    {
      t: 'p',
      text: 'The commercial consequence is not that generative work cannot be owned. It is that ownership is less automatic than everybody is used to, so it has to be constructed rather than assumed.',
    },
    { t: 'h2', text: 'The four clauses that actually decide it' },
    {
      t: 'table',
      caption: 'What to check before signing',
      head: ['Clause', 'The question', 'The answer you want'],
      rows: [
        [
          'Platform terms',
          'What does the model provider grant you in the output?',
          'An unambiguous commercial grant, on the plan you are actually on. Free tiers frequently differ.',
        ],
        [
          'Assignment',
          'What does the studio assign to the client, and when?',
          'All assignable rights in the deliverables, on payment, including the project files and the lock file.',
        ],
        [
          'Warranty and indemnity',
          'Who carries the risk if a third party claims the output infringes?',
          'Somebody, explicitly. An agreement silent on this has allocated the risk to whoever gets sued.',
        ],
        [
          'Third-party material',
          'Are references, likenesses, music or trained identities cleared?',
          'A schedule listing every input and its clearance. This is the clause that saves projects.',
        ],
      ],
    },
    {
      t: 'p',
      text: 'The fourth is the one most often missing and the most likely to matter. Almost every real dispute we have seen in this area concerned an input rather than an output: a reference image somebody did not have rights to, a likeness without a release, a piece of music cleared for one use and running in another.',
    },
    {
      t: 'note',
      title: 'Ownership and exclusivity are different questions',
      text: 'You can own everything assignable in an asset and still not be able to stop a similar one existing, because a model can produce something similar for somebody else. If exclusivity matters — a character, a presenter, a signature look — it has to be constructed from trained assets and contract terms, not assumed from ownership.',
    },
    { t: 'h2', text: 'What to actually secure in a deliverable' },
    {
      t: 'ol',
      items: [
        'The finished assets, in the delivery formats, with no dependency on any account or subscription.',
        'The project files: edit timelines, composites, layered masters.',
        'The lock file and the reference set, which is what allows the work to be continued by somebody else.',
        'The consent files for every real person whose likeness or voice appears, held by the client and not only by the studio.',
        'The input schedule: what went in, where it came from, and what clearance it carries.',
        'The run log, if provenance or substantiation is likely to be questioned later.',
      ],
    },
    {
      t: 'p',
      text: 'A deliverable that requires a specific model, seed or account to still exist is access rather than ownership, and it is worth naming that distinction during negotiation rather than discovering it during a re-version.',
    },
    { t: 'h2', text: 'The trained identity case' },
    {
      t: 'p',
      text: 'A trained character or presenter raises its own questions because the artefact is a model rather than an asset. Who holds the weights, who may use them, for what, for how long, and what happens at the end of the term all need stating.',
    },
    {
      t: 'p',
      text: 'If the training material came from a real person, their release has to grant the derivative-training right explicitly and should specify disposal at the end of term. A release drafted for photography does not cover this, because the concept did not exist when the wording was settled.',
    },
    { t: 'h2', text: 'A workable position for both sides' },
    {
      t: 'p',
      text: 'The arrangement that has held up in practice: the studio warrants that it holds or has cleared every input, assigns all assignable rights in the deliverables on payment, and hands over the files that make the work continuable. The client accepts that copyright in machine-generated components may be thin and that exclusivity comes from trained assets and contract terms rather than from the fact of generation.',
    },
    {
      t: 'p',
      text: 'That is honest on both sides, which is a better foundation than an assignment clause that promises more than the law currently supplies.',
    },
    {
      t: 'cta',
      href: '/supply-drop/synthetic-media-production-brief-template',
      label: 'The brief template',
      text: 'Where rights, clearance and the deliverable specification sit in a brief, before any of this becomes a negotiation.',
    },
  ],
  faqs: [
    {
      q: 'Who owns AI-generated content?',
      a: 'In most major jurisdictions copyright requires human authorship, so purely machine-generated output may attract thin protection or none. What tends to attract protection is the human contribution around it — selection, arrangement, editing, compositing and sequencing — which is why a finished film assembled by people is treated differently from a single raw output.',
    },
    {
      q: 'Can you use AI-generated images commercially?',
      a: 'Generally yes, subject to the model provider’s terms, which differ by plan and sometimes differ on free tiers. The riskier question is usually the inputs rather than the output: references, likenesses and music each need their own clearance.',
    },
    {
      q: 'What contract clauses decide ownership of generative work?',
      a: 'Four: what the platform terms grant in the output, what the studio assigns and when, who carries warranty and indemnity if a third party claims infringement, and a schedule listing every third-party input and its clearance. The last is most often missing and most likely to matter.',
    },
    {
      q: 'Is owning AI output the same as having exclusivity?',
      a: 'No. You can own everything assignable in an asset and still be unable to prevent a similar one existing, because a model can produce something similar for somebody else. Exclusivity has to be constructed from trained assets and contract terms.',
    },
    {
      q: 'What should you receive as deliverables from a generative production?',
      a: 'Finished assets with no account dependency, project files, the lock file and reference set, consent files for every real person, an input schedule with clearances, and the run log where provenance may be questioned. Anything requiring a specific model or account to still exist is access, not ownership.',
    },
    {
      q: 'Who owns a trained character model?',
      a: 'It has to be stated, because the artefact is a model rather than an asset: who holds the weights, who may use them, for what, for how long, and what happens at end of term. If the training material came from a real person, their release must grant the derivative-training right explicitly and specify disposal.',
    },
  ],
  terms: ['model-licence', 'derivative-training', 'likeness-rights', 'trained-identity', 'consent-file', 'deliverable-specification'],
  related: [
    'content-credentials-c2pa-for-brands',
    'synthetic-ugc-consent-likeness-and-disclosure-checklist',
    'how-to-choose-an-ai-video-production-agency',
  ],
  resources: ['synthetic-media-production-brief-template', 'synthetic-ugc-consent-template'],
  legalNotice: true,
};
